import img1 from '../accests/images/products/01.png'
import img2 from '../accests/images/products/02.png'
import img3 from '../accests/images/products/03.png'
import img4 from '../accests/images/products/04.png'
import img5 from '../accests/images/products/05.png'
import img6 from '../accests/images/products/06.png'
import img7 from '../accests/images/products/07.png'
import img8 from '../accests/images/products/08.png'
import img9 from '../accests/images/products/09.png'
export const dataProducts = [
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },

  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: null,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },
  {
    id: null,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: null,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: null,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
  {
    id: null,
    count: 0,
    img: img9,
    title: "Chinese Evergreen",
    price: 39,
    path: "/products/:chineseevergreen",
    type: "houseplants",
  },
];

for(let i=0; i < dataProducts.length; i++){
  let obj = dataProducts[i]
  obj.id = i
};

export const smallData = [
  {
    id: 1,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: 2,
    count: 0,
    img: img2,

    title: "Angel Wing Begonia",
    price: 169,
    path: "/products/:angelwinggegonia",
    type: "potterplants",
  },
  {
    id: 3,
    count: 0,
    img: img3,
    title: "African Violet",
    price: 199,
    path: "/products/:africanviolet",
    type: "smallplants",
  },
  {
    id: 4,
    count: 0,
    img: img4,
    title: "Beach Spider Lily",
    price: 129,
    path: "/products/:beachspiderlily",
    type: "smallplants",
  },
  {
    id: 5,
    count: 0,
    img: img5,
    title: "Blushing Bromeliad",
    price: 139,
    path: "/products/:blushingbromeliad",
    type: "bigplants",
  },
  {
    id: 6,
    count: 0,
    img: img1,
    title: "Barberton Daisy",
    price: 119,
    path: "/products/:barbertondaisy",
    type: "houseplants",
  },
  {
    id: 7,
    count: 0,
    img: img6,
    title: "Aluminum Plant",
    price: 179,
    path: "/products/:aluminumplant",
    type: "gardening",
  },
  {
    id: 8,
    count: 0,
    img: img7,
    title: "Broadleaf Lady Palm",
    price: 59,
    path: "/products/:broadleafladypalm",
    type: "potterplants",
  },

  {
    id: 9,
    count: 0,
    img: img8,
    title: "Bird's Nest Fern",
    price: 99,
    path: "/products/:birdsnestfern",
    type: "gardening",
  },
];